server:
  port: 7000
spring:
  application:
    name: SCW-USER
  datasource:
    url: jdbc:mysql://localhost:3306/zhongchou?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filter:
        stat:
          enabled: true
        wall:
          enabled: true
        config:
          enabled: true
      initial-size: 3    #初始化连接池的连接数量
      min-idle: 3      #最小空闲连接数
      max-active: 10 #最大连接数
      max-wait: 60000 #获取连接最大等待时间
      stat-view-servlet:
        url-pattern: /druid/*  #配置数据连接池管理控制台访问地址
        login-username: admin
        login-password: admin
        enabled: true   #开启管理控制台
        allow: 127.0.0.1  #设置允许访问客户端ip
  redis:
    host: 192.168.188.128
    port: 6379
mybatis:
  mapper-locations: classpath:/com/offcn/user/mapper/*.xml  #设置mybatis映射文件所在目录
  config-location: classpath:/mybatis/mybatis.xml  #设置mybatis本地配置文件
  type-aliases-package: com.offcn.user.po
logging:
  level:
    com:
      offcn: debug
sms:
  host: http://dingxin.market.alicloudapi.com
  path: /dx/sendSms
  method: POST
  tpl_id: TP1711063
  appcode: 441b41b4bccb4f89b640b5c23733f2f8



